### ISSUE TITLE
Please add me (flulemon) to the triagers team

### ISSUE THREAD

**Issue by flulemon** [aio-libs/triagers#23]
**What's your background?**
I'm a backend software engineer (currently at Meta), I've been using Python for many years and I've used aiohttp in couple of the projects. So I'd be happy to contribute.

**What's your motivation?**
I'd like to get some experience in the Open Source Development (so far I've only done Commercial development). I expect to help with fixing bugs, adding new tests (so we can get to aspirational 100% codecov) and any other useful stuff.

**Comment by Dreamsorcerer** [comment]
Sorry for the delay. It sounds like you want to contribute to the code, rather than triage bugs, so it doesn't sound like the triagers team is useful to you. You can start contributing without joining a team, just find some issues you want to work on and open some PRs.

Let me know if I understood that wrong or you have any other questions.
